### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by skypper** [kessiler/DFA#1]
I want to use [Sourcegraph](https://sourcegraph.com) for DFA code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/kessiler/DFA. (It should only take 30 seconds.)

Thank you!

**Comment by kessiler** [comment]
Sourcegraph enabled for this repository. But I did not look any difference regarding the issue on github.
